name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes
  
  $CHANGES

  categories:
    - title: 'ğŸš€ Features'
      labels:
        - 'docs: algorithm'
    - title: 'ğŸ› Bug Fixes'
      labels:
        - 'bug'
    - title: 'ğŸ§° Maintenance'
      labels:
        - 'dev experience'
        - 'enhancement'
        - 'dependencies'
