name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    types:
      - 'add'
      - 'update'
  - title: 'ğŸ› Bug Fixes'
    types:
      - 'fix'
  - title: 'ğŸ§° Maintenance'
    types:
      - 'build'
      - 'remove'
      - 'revert'
  - title: 'test labels'
      labels:
        - 'docs: algorithm'
        - 'dev experience'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes
  
  $CHANGES
